name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        find . -name "*.java" > sources.txt
        javac @sources.txt

    
    - name: Run Java programs (Optional)
      run: |
        echo "Run individual programs if needed manually"    